// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx79sGvvNnLzFDujfP5WwZu1tHZ8N6j-A',
    appId: '1:972576164217:web:2dfd4c59cad2ec7e55c7a8',
    messagingSenderId: '972576164217',
    projectId: 'trial01-31abe',
    authDomain: 'trial01-31abe.firebaseapp.com',
    storageBucket: 'trial01-31abe.appspot.com',
    measurementId: 'G-359V1BG440',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCITd2VAXsnjqXjkb4qF9xsxloP9wiJcY0',
    appId: '1:972576164217:android:0d3faa9719193e9955c7a8',
    messagingSenderId: '972576164217',
    projectId: 'trial01-31abe',
    storageBucket: 'trial01-31abe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARA0SUecZ28ZIRl8s16nsdgt3ckgKBpXY',
    appId: '1:972576164217:ios:4ad9a7284e0ffbd355c7a8',
    messagingSenderId: '972576164217',
    projectId: 'trial01-31abe',
    storageBucket: 'trial01-31abe.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx79sGvvNnLzFDujfP5WwZu1tHZ8N6j-A',
    appId: '1:972576164217:web:01bb04d39fe2186a55c7a8',
    messagingSenderId: '972576164217',
    projectId: 'trial01-31abe',
    authDomain: 'trial01-31abe.firebaseapp.com',
    storageBucket: 'trial01-31abe.appspot.com',
    measurementId: 'G-6DZ33QYBVL',
  );
}
